# Generated by Django 5.2.8 on 2025-12-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_component_is_approved_component_local_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='likes',
        ),
    ]
